### ISSUE TITLE
Original authors repo is on github

### ISSUE THREAD

**Issue by pstray** [hierotex/hierotex#27]
The original author has put up his copy at rosmord/HieroTeX

**Comment by mike42** [comment]
Hi @pstray, thanks for noticing!

This is my attempt at continuing HieroTeX under a community-development model. Serge is also an owner in the [hierotex](https://github.com/orgs/hierotex/people) organisation, and is aware of this repo.

Hopefully some other HieroTeX users join us soon, but there are not many of us, I guess. :)

**Comment by pstray** [comment]
Ah ok... not easy to see that, as none of the members are public :)
Anyways, would possibly be nicer if the two repos were linked here on github...
